### ISSUE TITLE
Geolite related error

### ISSUE THREAD

**Issue by rroblik** [crazy-max/docker-matomo#34]
#### Steps to reproduce this issue

1. Run docker image `crazymax/matomo:3.13.1` in (based on [this docker-compose file](https://github.com/crazy-max/docker-matomo/blob/master/examples/swarm/docker-compose.yml) but **without** `crazymax/geoip-updater` service.
2. Start the stack

#### Expected behaviour

As no `.mmdb` file provided in `/data/geoip` : nothing related to geoip should happen.

#### Actual behaviour

3 empty files are created empty : 
```
/data/geoip/GeoLite2-ASN.mmdb
/data/geoip/GeoLite2-City.mmdb
/data/geoip/GeoLite2-Country.mmdb
```

Fatal error (see log bellow)

### Logs

```
...
2020/01/31 15:04:18 [emerg] 170#170: MMDB_open("/data/geoip/GeoLite2-ASN.mmdb") failed - An attempt to read data from the MaxMind DB file failed in /etc/nginx/geoip2-asn.conf:1,
nginx: [emerg] MMDB_open("/data/geoip/GeoLite2-ASN.mmdb") failed - An attempt to read data from the MaxMind DB file failed in /etc/nginx/geoip2-asn.conf:1,
2020-01-31 15:04:18,525 INFO exited: nginx (exit status 1; not expected),
Setting up watches.,
Watches established.
...
```

**Comment by crazy-max** [comment]
Hi @rroblik,

Can you give me the complete logs please?

**Comment by rroblik** [comment]
For sure, here is :

```log
Setting PHP-FPM configuration...,
Setting OpCache configuration...,
Setting Nginx configuration...,
Setting SSMTP configuration...,
WARNING: SSMTP_HOST must be defined if you want to send emails,
Initializing Matomo files / folders...,
ecking Matomo plugins...,
  - Adding API,
  - Adding Actions,
  - Adding Annotations,
  - Adding BulkTracking,
  - Adding Contents,
  - Adding CoreAdminHome,
  - Adding CoreConsole,
  - Adding CoreHome,
  - Adding CorePluginsAdmin,
  - Adding CoreUpdater,
  - Adding CoreVisualizations,
  - Adding CustomDimensions,
  - Adding CustomPiwikJs,
  - Adding CustomVariables,
  - Adding Dashboard,
  - Adding DevicePlugins,
  - Adding DevicesDetection,
  - Adding Diagnostics,
  - Adding Ecommerce,
  - Adding Events,
  - Adding Feedback,
  - Adding GeoIp2,
  - Adding Goals,
  - Adding Heartbeat,
  - Adding ImageGraph,
  - Adding Insights,
  - Adding Installation,
  - Adding Intl,
  - Adding IntranetMeasurable,
  - Adding LanguagesManager,
  - Adding Live,
  - Adding LogViewer,
  - Adding Login,
  - Adding LoginSaml,
  - Adding Marketplace,
  - Adding MobileMessaging,
  - Adding Monolog,
  - Adding Morpheus,
  - Adding MultiSites,
  - Adding Overlay,
  - Adding PierreFabre,
  - Adding PrivacyManager,
  - Adding ProfessionalServices,
  - Adding Proxy,
  - Adding Referrers,
  - Adding Resolution,
  - Adding RssWidget,
  - Adding SEO,
  - Adding ScheduledReports,
  - Adding SegmentEditor,
  - Adding SitesManager,
  - Adding Tour,
  - Adding Transitions,
  - Adding TwoFactorAuth,
  - Adding UserCountry,
  - Adding UserCountryMap,
  - Adding UserId,
  - Adding UserLanguage,
  - Adding UsersManager,
  - Adding VisitFrequency,
  - Adding VisitTime,
  - Adding VisitorInterest,
  - Adding VisitsSummary,
  - Adding WebsiteMeasurable,
  - Adding Widgetize,
Checking Matomo user-misc folder...,
Fixing permissions...,
Setting Matomo log level to WARN...,
Setting [log] log_level = "WARN"... done.,
Upgrading and setting Matomo configuration...,
,
    *** Update ***,
,
    Database Upgrade Required,
,
    Your Matomo database is out-of-date, and must be upgraded before you can continue.,
,
    Matomo database will be upgraded from version 3.13.0 to the new version 3.13.1.,
,
ERROR [2020-02-03 08:06:14] 150  Uncaught exception: Error: Call to undefined method Piwik\Plugins\GeoIp2\LocationProvider\GeoIp2::getDbIpLiteUrl() in /var/www/core/Updates/3.13.1-b2.php:40,
Stack trace:,
#0 /var/www/core/Updater.php(256): Piwik\Updates\Updates_3_13_1_b2->getMigrations(Object(Piwik\Updater)),
#1 /data/plugins/CoreUpdater/Commands/Update.php(341): Piwik\Updater->getSqlQueriesToExecute(),
#2 /data/plugins/CoreUpdater/Commands/Update.php(159): Piwik\Plugins\CoreUpdater\Commands\Update->getMigrationQueriesToExecute(Object(Piwik\Updater)),
#3 /data/plugins/CoreUpdater/Commands/Update.php(151): Piwik\Plugins\CoreUpdater\Commands\Update->doDryRun(Object(Piwik\Updater), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#4 /data/plugins/CoreUpdater/Commands/Update.php(57): Piwik\Plugins\CoreUpdater\Commands\Update->makeUpdate(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), true),
#5 /var/www/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreUpdater\Commands\Update->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#6 /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#7 /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreUpdater\Commands\Update), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#8 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#9 /var/www/core/Console.php(125): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#10 /var/www/core/Access.php(644): Piwik\Console->Piwik\{closure}(),
#11 /var/www/core/Console.php(126): Piwik\Access::doAsSuperUser(Object(Closure)),
#12 /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#13 /var/www/console(27): Symfony\Component\Console\Application->run(),
#14 {main},
Uncaught exception: Call to undefined method Piwik\Plugins\GeoIp2\LocationProvider\GeoIp2::getDbIpLiteUrl(),
in /var/www/core/Updates/3.13.1-b2.php line 40,
#0 /var/www/core/Updater.php(256): Piwik\Updates\Updates_3_13_1_b2->getMigrations(Object(Piwik\Updater)),
#1 /data/plugins/CoreUpdater/Commands/Update.php(341): Piwik\Updater->getSqlQueriesToExecute(),
#2 /data/plugins/CoreUpdater/Commands/Update.php(159): Piwik\Plugins\CoreUpdater\Commands\Update->getMigrationQueriesToExecute(Object(Piwik\Updater)),
#3 /data/plugins/CoreUpdater/Commands/Update.php(151): Piwik\Plugins\CoreUpdater\Commands\Update->doDryRun(Object(Piwik\Updater), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#4 /data/plugins/CoreUpdater/Commands/Update.php(57): Piwik\Plugins\CoreUpdater\Commands\Update->makeUpdate(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), true),
#5 /var/www/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\CoreUpdater\Commands\Update->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#6 /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#7 /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Piwik\Plugins\CoreUpdater\Commands\Update), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#8 [internal function]: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#9 /var/www/core/Console.php(125): call_user_func(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#10 /var/www/core/Access.php(644): Piwik\Console->Piwik\{closure}(),
#11 /var/www/core/Console.php(126): Piwik\Access::doAsSuperUser(Object(Closure)),
#12 /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)),
#13 /var/www/console(27): Symfony\Component\Console\Application->run(),
#14 {main},
Setting [General] minimum_memory_limit = "-1"... done.,
2020-02-03 09:06:14,608 INFO Included extra file "/etc/supervisord/matomo_watch_plugins.conf" during parsing,
2020-02-03 09:06:14,608 INFO Included extra file "/etc/supervisord/nginx.conf" during parsing,
2020-02-03 09:06:14,608 INFO Included extra file "/etc/supervisord/php.conf" during parsing,
2020-02-03 09:06:14,608 INFO Set uid to user 0 succeeded,
2020-02-03 09:06:14,615 INFO RPC interface 'supervisor' initialized,
2020-02-03 09:06:14,616 CRIT Server 'unix_http_server' running without any HTTP authentication checking,
2020-02-03 09:06:14,616 INFO supervisord started with pid 1,
2020-02-03 09:06:15,617 INFO spawned: 'nginx' with pid 154,
2020-02-03 09:06:15,618 INFO spawned: 'php' with pid 155,
2020-02-03 09:06:15,620 INFO spawned: 'matomo_watch_plugins' with pid 156,
Setting up watches.,
Watches established.,
[03-Feb-2020 09:06:15] NOTICE: fpm is running, pid 155,
[03-Feb-2020 09:06:15] NOTICE: ready to handle connections,
2020/02/03 09:06:15 [notice] 154#154: using the "epoll" event method,
2020/02/03 09:06:15 [notice] 154#154: nginx/1.17.8,
2020/02/03 09:06:15 [notice] 154#154: built by gcc 8.3.0 (Alpine 8.3.0) ,
2020/02/03 09:06:15 [notice] 154#154: OS: Linux 3.10.0-1062.4.3.el7.x86_64,
2020/02/03 09:06:15 [notice] 154#154: getrlimit(RLIMIT_NOFILE): 65536:65536,
2020/02/03 09:06:15 [notice] 154#154: start worker processes,
2020/02/03 09:06:15 [notice] 154#154: start worker process 161,
2020/02/03 09:06:15 [notice] 154#154: start worker process 162,
2020/02/03 09:06:15 [notice] 154#154: start worker process 163,
2020/02/03 09:06:15 [notice] 154#154: start worker process 164,
2020/02/03 09:06:15 [notice] 154#154: start worker process 165,
2020/02/03 09:06:15 [notice] 154#154: start worker process 166,
2020/02/03 09:06:15 [notice] 154#154: start worker process 167,
2020/02/03 09:06:15 [notice] 154#154: start worker process 168,
2020-02-03 09:06:16,698 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2020-02-03 09:06:16,698 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2020-02-03 09:06:16,698 INFO success: matomo_watch_plugins entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
```

**Comment by crazy-max** [comment]
Ok can you remove the empty files `rm -f /data/geoip/GeoLite2*` and restart your container?

**Comment by rroblik** [comment]
EDIT : Ok I think it's an issue related to GeoIP 2 module, which was left in `plugins` folder and so _automagically_ enabled during your image entrypoint :(

One GeoIP 2 folder removed statring is ok BUt I have only `default` Geoip option enabled in Matoo, any idea ?

**Comment by rroblik** [comment]
@crazy-max sorry for cross message !

I readded GeoIP 2 module, `rm -f /data/geoip/GeoLite2*` then restarted : no error but empty geo file created, no more geolocation option available in admin

![2020-02-03 09_34_15-Clipboard](https://user-images.githubusercontent.com/5805093/73637433-90e9b580-4668-11ea-8d5b-23d8c913480e.png)

**Comment by crazy-max** [comment]
@rroblik 

```
ecking Matomo plugins...,
  - Adding API,
  - Adding Actions,
  - Adding Annotations,
  - Adding BulkTracking,
  - Adding Contents,
  - Adding CoreAdminHome,
  - Adding CoreConsole,
  - Adding CoreHome,
  - Adding CorePluginsAdmin,
  - Adding CoreUpdater,
  - Adding CoreVisualizations,
  - Adding CustomDimensions,
  - Adding CustomPiwikJs,
  - Adding CustomVariables,
  - Adding Dashboard,
  - Adding DevicePlugins,
  - Adding DevicesDetection,
  - Adding Diagnostics,
  - Adding Ecommerce,
  - Adding Events,
  - Adding Feedback,
  - Adding GeoIp2,
  - Adding Goals,
  - Adding Heartbeat,
  - Adding ImageGraph,
  - Adding Insights,
  - Adding Installation,
  - Adding Intl,
  - Adding IntranetMeasurable,
  - Adding LanguagesManager,
  - Adding Live,
  - Adding LogViewer,
  - Adding Login,
  - Adding LoginSaml,
  - Adding Marketplace,
  - Adding MobileMessaging,
  - Adding Monolog,
  - Adding Morpheus,
  - Adding MultiSites,
  - Adding Overlay,
  - Adding PrivacyManager,
  - Adding ProfessionalServices,
  - Adding Proxy,
  - Adding Referrers,
  - Adding Resolution,
  - Adding RssWidget,
  - Adding SEO,
  - Adding ScheduledReports,
  - Adding SegmentEditor,
  - Adding SitesManager,
  - Adding Tour,
  - Adding Transitions,
  - Adding TwoFactorAuth,
  - Adding UserCountry,
  - Adding UserCountryMap,
  - Adding UserId,
  - Adding UserLanguage,
  - Adding UsersManager,
  - Adding VisitFrequency,
  - Adding VisitTime,
  - Adding VisitorInterest,
  - Adding VisitsSummary,
  - Adding WebsiteMeasurable,
  - Adding Widgetize,
```

Why do you have so many plugins in `/data/plugins`? Have you copy thos plugins from a previous Matomo install or something? I think this is the root cause of your issue. Can you clean this folder and keep ONLY plugins downloaded by yourself?

**Comment by rroblik** [comment]
Yes migrating from an existing 3.15.0 matomo installation (not dockerized)

Need all of them :)

**Comment by crazy-max** [comment]
Ok McFly, come back to 2020 please, 3.15.0 is not out yet at this time :rocket:

**Comment by rroblik** [comment]
Edited sorry :)

**Comment by crazy-max** [comment]
I'm sorry, but it's not going to work with this image if you keep core plugins from `3.13.0`...
If you want to use this image, remove all core plugins from `/data/plugins` and ONLY add plugins downloaded by yourself in `/data/plugins`.

**Comment by rroblik** [comment]
Will ask internally, but I think there is an (license) issue embedding maxmind files since st January 

BR
